out_dir: results/example_graphgym
train:
  batch_size: 1
  eval_period: 20
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 128
  layer_type: gcnconv
  stage_type: stack
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100
  scheduler: none
