version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
