version: 1
formatters:
  defaultFormatter:
    format: '%(name)s:%(funcName)s:%(levelname)s:%(message)s'
  briefFormatter:
    format: '%(message)s'
handlers:
  defaultConsoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: defaultFormatter
  briefConsoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: briefFormatter
loggers:
  defaultLogger:
    level: INFO
    handlers: [defaultConsoleHandler]
    propagate: no
  briefLogger:
    level: INFO
    handlers: [briefConsoleHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [defaultConsoleHandler]
