name: Examples on latest

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * 0'

jobs:
  run_examples:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]
        include:
          - torch-version: 1.12.1
            torchvision-version: 0.13.1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.torch-version }}+cpu torchvision==${{ matrix.torchvision-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-scatter torch-scatter torch-cluster -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
          pip install git+https://github.com/pyg-team/pytorch_geometric.git#egg=torch-geometric[full]
          pip install -r requirements.txt

      - name: Install NLEval
        run: |
          pip install -e .

      - name: Execute example scripts
        shell: bash
        run: |
          cd example
          for script in $(ls *.py); do
            if [[ $script == n2v_hypertune_studybias_holdout.py ]] || [[ $script == sample_classification.py ]]; then
              continue
            fi
            echo Start runing example script: $script
            python $script
          done
